// import {AppProvider} from "@/components/AppContext";
// import Header from "@/components/layout/Header";
// import { Roboto } from 'next/font/google'
// import './globals.css'
// import {Toaster} from "react-hot-toast";
// import NextAuthProvider from './common/NextAuthProvider'
// import { getServerSession } from 'next-auth'
// const roboto = Roboto({ subsets: ['latin'], weight: ['400', '500', '700'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({ 
//   children, }) {
//     const session=  getServerSession();
//   return (
//     <html lang="en" className="scroll-smooth">
//       <body className={roboto.className}>
//       <NextAuthProvider session={session}>
//         <main className="max-w-4xl mx-auto p-4">
//           <AppProvider>
//             <Toaster />
//             <Header />
//             {children}
//             <footer className="border-t p-8 text-center text-gray-500 mt-16">
//               &copy; 2023 All rights reserved
//             </footer>
//           </AppProvider>
//         </main>
//          </NextAuthProvider> {/*added by nextauthurl file  */}
//       </body>
//     </html>
//   )
// }

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import NextAuthProvider from './common/NextAuthProvider'
import { getServerSession } from 'next-auth'
// import Navbar from './components/Navbar'
// import NavarBar from './components/NavarBar'
import {AppProvider} from "@/components/AppContext";
import Header from "@/components/layout/Header";
import { Roboto } from 'next/font/google'
// import './globals.css'
import {Toaster} from "react-hot-toast";
// import NextAuthProvider from './common/NextAuthProvider'
// import { getServerSession } from 'next-auth'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session= await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider session={session}>
        <main className="max-w-4xl mx-auto p-4">
   <AppProvider>
     <Toaster />
     <Header />
     {children}
     <footer className="border-t p-8 text-center text-gray-500 mt-16">
       &copy; 2023 All rights reserved
     </footer>
   </AppProvider>
   </main>
        </NextAuthProvider>
        </body>

    </html>
  )
}
